version: "3.5"
services:
    mysql:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'RwJ8XJkqK3ohMtBdk2sReu3zUA5AfBHDVPpKxLMAYuQna2tHPSgymSbmVyog2nYh'
            MYSQL_DATABASE: 'payment'
        ports:
            - "127.0.0.1:3306:3306" # Mapped to localhost to only allow access from this machine
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
            - ./.docker/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - default
    php:
        build: ./.docker/php
        depends_on:
            - mysql
        volumes:
            - ./dist:/var/www/html/
        networks:
            - default
    httpd:
        build: ./.docker/httpd
        depends_on:
            - php
        ports:
            - "127.0.0.1:80:80" # Mapped to localhost to only allow access from this machine
        volumes:
            - ./dist:/var/www/html/
        networks:
            - default
    tests:
        build: ./.docker/tests
        depends_on:
            - mysql
        environment:
            - COMPOSER_CACHE_DIR=/host_shared_cache/var/cache/composer
        volumes:
            - ./.docker/tests/cache:/host_shared_cache
            - ./:/var/www/html/
networks:
    default: